### PR TITLE
Add zh-cn locale

### PR DESCRIPTION
**Pull request by Riajyuu**
Sorry for bothering.
Correct me if there is any mistake.

### CODE REVIEW

**Comment by fregante** [comment]
It looks good! You should see a new version published soon. 

Let me know if it looks right.

Should we also translate the extension name?

**Comment by Riajyuu** [comment]
> Should we also translate the extension name?

@bfred-it If you'd like to, I suggest `GitHub首页消息新颜` , which literal means `new look of GitHub homepage news feed`

But frankly, most add-ons won't have name localized as far as I know

**Comment by fregante** [comment]
Ok then, no translation necessary :)

**Comment by fregante** [comment]
This version is now available for both Chrome and Firefox

**Comment by Riajyuu** [comment]
@bfred-it I download 17.6.1.842 at https://addons.mozilla.org/zh-CN/firefox/addon/github-clean-feed/

But everything is still English. Is there anything I missed?

**Comment by fregante** [comment]
Ah I think the folder was supposed to be called `zh_CN`

I renamed it and you should see version .1031 soon

**Comment by Riajyuu** [comment]
@bfred-it sorry to take such a long time.
I have downloaded version .1031 from [zh-cn version of AMO](https://addons.mozilla.org/zh-CN) but it si still English.

Do I have to use Chinese version of Firefox?

**Comment by fregante** [comment]
Yes. The language depends on your browser's locale

**Comment by Riajyuu** [comment]
@bfred-it Things are wired: the option "disappeared" and only strings are displayed:
image

**Comment by fregante** [comment]
I downloaded this version and I see it correctly: https://www.mozilla.org/zh-CN/firefox/new/

GitHub Clean Feed 17.6.1.1031 in Firefox v53 zh-CN

**Pull request merged**
